
INSERT INTO admins (name, surname) VALUES ('Gabriela', 'Topczewska');
INSERT INTO admins (name, surname) VALUES ('Aleksandra', 'Majewska');
INSERT INTO admins (name, surname) VALUES ('Rados³aw', 'Kostrzewski');
INSERT INTO admins (name, surname) VALUES ('Aleksandra', 'Jamróz');
commit;

--------------------------------------------------------------------------------

INSERT INTO countries VALUES (1, 'Polska');
INSERT INTO countries VALUES (2, 'Niemcy');
INSERT INTO countries VALUES (3, 'Francja');
INSERT INTO countries VALUES (4, 'Wielka Brytania');
INSERT INTO countries VALUES (5, 'Czechy');
INSERT INTO countries VALUES (6, 'Litwa');
INSERT INTO countries VALUES (7, 'Ukraina');
INSERT INTO countries VALUES (8, 'S³owacja');
INSERT INTO countries VALUES (9, 'Norwegia');
INSERT INTO countries VALUES (10, 'Szwecja');
INSERT INTO countries VALUES (11, 'Finlandia');
INSERT INTO countries VALUES (12, 'Hiszpania');
INSERT INTO countries VALUES (13, 'Republika Po³udniowej Ameryki');
INSERT INTO countries VALUES (14, 'Egipt');
INSERT INTO countries VALUES (15, 'Izrael');
INSERT INTO countries VALUES (16, 'Irak');
INSERT INTO countries VALUES (17, 'Turcja');
INSERT INTO countries VALUES (18, 'Stany Zjednoczone Ameryki');
INSERT INTO countries VALUES (19, 'Kanada');
INSERT INTO countries VALUES (20, 'Brazylia');
INSERT INTO countries VALUES (21, 'Argentyna');
INSERT INTO countries VALUES (22, 'Chiñska Republika Ludowa');
INSERT INTO countries VALUES (23, 'Japonia');
INSERT INTO countries VALUES (24, 'Korea Po³udniowa');
INSERT INTO countries VALUES (25, 'Rosja');
INSERT INTO countries VALUES (26, 'Gruzja');
commit;

--------------------------------------------------------------------------------

INSERT INTO voivodships (name)VALUES ('DOLNOŒL¥SKIE', 1);
INSERT INTO voivodships (name)VALUES('KUJAWSKO-POMORSKIE', 1);
INSERT INTO voivodships (name)VALUES('LUBELSKIE', 1);
INSERT INTO voivodships (name)VALUES('LUBUSKIE', 1);
INSERT INTO voivodships (name)VALUES('£ÓDZKIE', 1);
INSERT INTO voivodships (name)VALUES('MA£OPOLSKIE', 1);
INSERT INTO voivodships (name)VALUES('MAZOWIECKIE', 1);
INSERT INTO voivodships (name)VALUES('OPOLSKIE', 1);
INSERT INTO voivodships (name)VALUES('PODKARPACKIE', 1);
INSERT INTO voivodships (name)VALUES('PODLASKIE', 1);
INSERT INTO voivodships (name)VALUES('POMORSKIE', 1);
INSERT INTO voivodships (name)VALUES('ŒL¥SKIE', 1);
INSERT INTO voivodships (name)VALUES('ŒWIÊTOKRZYSKIE', 1);
INSERT INTO voivodships (name)VALUES('WARMIÑSKO-MAZURSKIE', 1);
INSERT INTO voivodships (name)VALUES('WIELKOPOLSKIE', 1);
INSERT INTO voivodships (name)VALUES('ZACHODNIOPOMORSKIE', 1);
commit;

--------------------------------------------------------------------------------

INSERT INTO cities (voivodship_id, name) VALUES (14, 'Warszawa');
INSERT INTO cities (voivodship_id, name) VALUES (2, 'Boles³awiec');
INSERT INTO cities (voivodship_id, name) VALUES (2, 'Nowogrodziec');
INSERT INTO cities (voivodship_id, name) VALUES (2, 'Bielawa');
INSERT INTO cities (voivodship_id, name) VALUES (2, 'Dzier¿oniów');
INSERT INTO cities (voivodship_id, name) VALUES (2, 'Pieszyce');
INSERT INTO cities (voivodship_id, name) VALUES (2, 'Pi³awa Górna');
INSERT INTO cities (voivodship_id, name) VALUES (2, 'Niemcza');
INSERT INTO cities (voivodship_id, name) VALUES (2, 'G³ogów');
INSERT INTO cities (voivodship_id, name) VALUES (2, 'Góra');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'W¹sosz');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Jawor');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Bolków');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Karpacz');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Kowary');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Piechowice');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Szklarska Porêba');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Kamienna Góra');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Lubawka');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Duszniki-Zdrój');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'K³odzko');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Kudowa-Zdrój');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Nowa Ruda');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Polanica-Zdrój');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Bystrzyca K³odzka');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'L¹dek-Zdrój');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Miêdzylesie');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Radków');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Stronie Œl¹skie');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Szczytna');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Chojnów');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Prochowice');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Lubañ');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Œwieradów-Zdrój');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Leœna');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Olszyna');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Lubin');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Œcinawa');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Gryfów Œl¹ski');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Lubomierz');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Lwówek Œl¹ski');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Mirsk');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Wleñ');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Milicz');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Oleœnica');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Bierutów');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Miêdzybórz');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Syców');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Twardogóra');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'O³awa');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Jelcz-Laskowice');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Chocianów');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Polkowice');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Przemków');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Strzelin');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Wi¹zów');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Œroda Œl¹ska');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Œwidnica');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Œwiebodzice');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Jaworzyna Œl¹ska');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Strzegom');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, '¯arów');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Oborniki Œl¹skie');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Prusice');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Trzebnica');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, '¯migród');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Boguszów-Gorce');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Jedlina-Zdrój');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Szczawno-Zdrój');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'G³uszyca');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Mieroszów');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Brzeg Dolny');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Wo³ów');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'K¹ty Wroc³awskie');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Sobótka');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Siechnice');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Bardo');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Z¹bkowice Œl¹skie');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Ziêbice');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Z³oty Stok');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Zawidów');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Zgorzelec');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Bogatynia');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Pieñsk');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Wêgliniec');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Wojcieszów');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Z³otoryja');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Œwierzawa');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Jelenia Góra');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Legnica');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Wroc³aw');
INSERT INTO cities (voivodship_id, name) VALUES ( 2, 'Wa³brzych');
INSERT INTO cities (voivodship_id, name) VALUES ( 4, 'Aleksandrów Kujawski');
INSERT INTO cities (voivodship_id, name) VALUES ( 4, 'Ciechocinek');
INSERT INTO cities (voivodship_id, name) VALUES ( 4, 'Nieszawa');
INSERT INTO cities (voivodship_id, name) VALUES ( 4, 'Brodnica');
INSERT INTO cities (voivodship_id, name) VALUES ( 4, 'Górzno');
INSERT INTO cities (voivodship_id, name) VALUES ( 4, 'Jab³onowo Pomorskie');
INSERT INTO cities (voivodship_id, name) VALUES ( 4, 'Koronowo');
INSERT INTO cities (voivodship_id, name) VALUES ( 4, 'Solec Kujawski');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Che³mno');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Golub-Dobrzyñ');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Kowalewo Pomorskie');
INSERT INTO cities (voivodship_id, name) VALUES (4, '£asin');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Radzyñ Che³miñski');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Inowroc³aw');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Gniewkowo');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Janikowo');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Kruszwica');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Pakoœæ');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Lipno');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Dobrzyñ nad Wis³¹');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Skêpe');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Mogilno');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Strzelno');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Kcynia');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Mrocza');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Nak³o nad Noteci¹');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Szubin');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Radziejów');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Piotrków Kujawski');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Rypin');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Kamieñ Krajeñski');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Sêpólno Krajeñskie');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Wiêcbork');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Nowe');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Œwiecie');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Che³m¿a');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Tuchola');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'W¹brzeŸno');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Kowal');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Brzeœæ Kujawski');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Chodecz');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Izbica Kujawska');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Lubieñ Kujawski');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Lubraniec');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Barcin');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Janowiec Wielkopolski');
INSERT INTO cities (voivodship_id, name) VALUES (4, '£abiszyn');
INSERT INTO cities (voivodship_id, name) VALUES (4, '¯nin');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Bydgoszcz');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Grudzi¹dz');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'Toruñ');
INSERT INTO cities (voivodship_id, name) VALUES (4, 'W³oc³awek');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Miêdzyrzec Podlaski');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Terespol');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Bi³goraj');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Frampol');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Józefów');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Tarnogród');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Rejowiec Fabryczny');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Siedliszcze');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Hrubieszów');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Janów Lubelski');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Modliborzyce');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Krasnystaw');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Kraœnik');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Annopol');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Urzêdów');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Lubartów');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Kock');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Ostrów Lubelski');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Be³¿yce');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Bychawa');
INSERT INTO cities (voivodship_id, name) VALUES (6, '£êczna');
INSERT INTO cities (voivodship_id, name) VALUES (6, '£uków');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Stoczek £ukowski');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Opole Lubelskie');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Poniatowa');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Parczew');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Pu³awy');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Kazimierz Dolny');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Na³êczów');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Radzyñ Podlaski');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Dêblin');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Ryki');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Œwidnik');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Piaski');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Tomaszów Lubelski');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Lubycza Królewska');
INSERT INTO cities (voivodship_id, name) VALUES (6, '£aszczów');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Tyszowce');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'W³odawa');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Krasnobród');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Szczebrzeszyn');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Zwierzyniec');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Bia³a Podlaska');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Che³m');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Lublin');
INSERT INTO cities (voivodship_id, name) VALUES (6, 'Zamoœæ');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Kostrzyn nad Odr¹');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Witnica');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Gubin');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Krosno Odrzañskie');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Miêdzyrzecz');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Skwierzyna');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Trzciel');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Nowa Sól');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Bytom Odrzañski');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Ko¿uchów');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Nowe Miasteczko');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Cybinka');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Oœno Lubuskie');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Rzepin');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'S³ubice');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Dobiegniew');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Drezdenko');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Strzelce Krajeñskie');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Lubniewice');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Sulêcin');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Torzym');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Œwiebodzin');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Zb¹szynek');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Babimost');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Czerwieñsk');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Kargowa');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Nowogród Bobrzañski');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Sulechów');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Gozdnica');
INSERT INTO cities (voivodship_id, name) VALUES (8, '¯agañ');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'I³owa');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Ma³omice');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Szprotawa');
INSERT INTO cities (voivodship_id, name) VALUES (8, '£êknica');
INSERT INTO cities (voivodship_id, name) VALUES (8, '¯ary');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Jasieñ');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Lubsko');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'S³awa');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Szlichtyngowa');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Wschowa');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Gorzów Wielkopolski');
INSERT INTO cities (voivodship_id, name) VALUES (8, 'Zielona Góra');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Be³chatów');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Zelów');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Kutno');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Kroœniewice');
INSERT INTO cities (voivodship_id, name) VALUES (10, '¯ychlin');
INSERT INTO cities (voivodship_id, name) VALUES (10, '£ask');
INSERT INTO cities (voivodship_id, name) VALUES (10, '£êczyca');
INSERT INTO cities (voivodship_id, name) VALUES (10, '£owicz');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Koluszki');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Rzgów');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Tuszyn');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Drzewica');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Opoczno');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Konstantynów £ódzki');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Pabianice');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Dzia³oszyn');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Pajêczno');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Sulejów');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Wolbórz');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Poddêbice');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Uniejów');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Radomsko');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Kamieñsk');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Przedbórz');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Rawa Mazowiecka');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Bia³a Rawska');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Sieradz');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'B³aszki');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Warta');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Z³oczew');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Tomaszów Mazowiecki');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Wieluñ');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Wieruszów');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Zduñska Wola');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Szadek');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'G³owno');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Ozorków');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Zgierz');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Aleksandrów £ódzki');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Stryków');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Brzeziny');
INSERT INTO cities (voivodship_id, name) VALUES (10, '£ódŸ');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Piotrków Trybunalski');
INSERT INTO cities (voivodship_id, name) VALUES (10, 'Skierniewice');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Bochnia');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Nowy Wiœnicz');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Brzesko');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Czchów');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Alwernia');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Chrzanów');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Libi¹¿');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Trzebinia');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'D¹browa Tarnowska');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Szczucin');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Gorlice');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Biecz');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Bobowa');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Krzeszowice');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Ska³a');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Skawina');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'S³omniki');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Œwi¹tniki Górne');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Limanowa');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Mszana Dolna');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Miechów');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Dobczyce');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Myœlenice');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Su³kowice');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Grybów');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Krynica-Zdrój');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Muszyna');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Piwniczna-Zdrój');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Stary S¹cz');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Nowy Targ');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Szczawnica');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Rabka-Zdrój');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Bukowno');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Olkusz');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Wolbrom');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Oœwiêcim');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Brzeszcze');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Che³mek');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Kêty');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Zator');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Nowe Brzesko');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Proszowice');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Jordanów');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Sucha Beskidzka');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Maków Podhalañski');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Ciê¿kowice');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Rad³ów');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Ryglice');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Tuchów');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Wojnicz');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Zakliczyn');
INSERT INTO cities (voivodship_id, name) VALUES (12, '¯abno');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Zakopane');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Andrychów');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Kalwaria Zebrzydowska');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Wadowice');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Niepo³omice');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Wieliczka');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Kraków');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Nowy S¹cz');
INSERT INTO cities (voivodship_id, name) VALUES (12, 'Tarnów');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Bia³obrzegi');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Wyœmierzyce');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Ciechanów');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Glinojeck');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Garwolin');
INSERT INTO cities (voivodship_id, name) VALUES (14, '£askarzew');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Pilawa');
INSERT INTO cities (voivodship_id, name) VALUES (14, '¯elechów');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Gostynin');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Milanówek');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Podkowa Leœna');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Grodzisk Mazowiecki');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Grójec');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Mogielnica');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Nowe Miasto nad Pilic¹');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Warka');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Kozienice');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Legionowo');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Serock');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Lipsko');
INSERT INTO cities (voivodship_id, name) VALUES (14, '£osice');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Maków Mazowiecki');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Ró¿an');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Miñsk Mazowiecki');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Halinów');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Ka³uszyn');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Mrozy');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Sulejówek');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'M³awa');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Nowy Dwór Mazowiecki');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Nasielsk');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Zakroczym');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Myszyniec');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Ostrów Mazowiecka');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Brok');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Józefów');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Otwock');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Karczew');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Góra Kalwaria');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Konstancin-Jeziorna');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Piaseczno');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Tarczyn');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Drobin');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'G¹bin');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Wyszogród');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'P³oñsk');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Raci¹¿');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Piastów');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Pruszków');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Brwinów');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Przasnysz');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Chorzele');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Przysucha');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Pu³tusk');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Pionki');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'I³¿a');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Skaryszew');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Mordy');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Sierpc');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Sochaczew');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Soko³ów Podlaski');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Kosów Lacki');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Szyd³owiec');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'B³onie');
INSERT INTO cities (voivodship_id, name) VALUES (14, '£omianki');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'O¿arów Mazowiecki');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Wêgrów');
INSERT INTO cities (voivodship_id, name) VALUES (14, '£ochów');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Koby³ka');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Marki');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Z¹bki');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Zielonka');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Radzymin');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'T³uszcz');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Wo³omin');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Wyszków');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Zwoleñ');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Bie¿uñ');
INSERT INTO cities (voivodship_id, name) VALUES (14, '¯uromin');
INSERT INTO cities (voivodship_id, name) VALUES (14, '¯yrardów');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Mszczonów');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Ostro³êka');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'P³ock');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Radom');
INSERT INTO cities (voivodship_id, name) VALUES (14, 'Siedlce');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Brzeg');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Grodków');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Lewin Brzeski');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Baborów');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'G³ubczyce');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Kietrz');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Kêdzierzyn-KoŸle');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Byczyna');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Kluczbork');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Wo³czyn');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Gogolin');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Krapkowice');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Zdzieszowice');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Namys³ów');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'G³ucho³azy');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Korfantów');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Nysa');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Otmuchów');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Paczków');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Dobrodzieñ');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Gorzów Œl¹ski');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Olesno');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Praszka');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Niemodlin');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Ozimek');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Prószków');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Bia³a');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'G³ogówek');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Prudnik');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Kolonowskie');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Leœnica');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Strzelce Opolskie');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Ujazd');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Zawadzkie');
INSERT INTO cities (voivodship_id, name) VALUES (16, 'Opole');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Ustrzyki Dolne');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Brzozów');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Dêbica');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Brzostek');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Pilzno');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Jaros³aw');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Radymno');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Pruchnik');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Jas³o');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Ko³aczyce');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Kolbuszowa');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Dukla');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Iwonicz-Zdrój');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Jedlicze');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Rymanów');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Le¿ajsk');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Nowa Sarzyna');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Lubaczów');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Cieszanów');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Narol');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Oleszyce');
INSERT INTO cities (voivodship_id, name) VALUES (18, '£añcut');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Mielec');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Przec³aw');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Radomyœl Wielki');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Nisko');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Rudnik nad Sanem');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Ulanów');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Przeworsk');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Kañczuga');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Sieniawa');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Ropczyce');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Sêdziszów Ma³opolski');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Dynów');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'B³a¿owa');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Boguchwa³a');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'G³ogów Ma³opolski');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Soko³ów Ma³opolski');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Tyczyn');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Sanok');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Zagórz');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Stalowa Wola');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Zaklików');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Strzy¿ów');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Baranów Sandomierski');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Nowa Dêba');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Lesko');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Krosno');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Przemyœl');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Rzeszów');
INSERT INTO cities (voivodship_id, name) VALUES (18, 'Tarnobrzeg');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Augustów');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Lipsk');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Choroszcz');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Czarna Bia³ostocka');
INSERT INTO cities (voivodship_id, name) VALUES (20, '£apy');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Micha³owo');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Supraœl');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Sura¿');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Tykocin');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Wasilków');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Zab³udów');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Bielsk Podlaski');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Brañsk');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Grajewo');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Rajgród');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Szczuczyn');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Hajnówka');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Kleszczele');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Kolno');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Stawiski');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Jedwabne');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Nowogród');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Goni¹dz');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Knyszyn');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Moñki');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Sejny');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Siemiatycze');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Drohiczyn');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'D¹browa Bia³ostocka');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Krynki');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Sokó³ka');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Suchowola');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Wysokie Mazowieckie');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Ciechanowiec');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Czy¿ew');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Szepietowo');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Zambrów');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Bia³ystok');
INSERT INTO cities (voivodship_id, name) VALUES (20, '£om¿a');
INSERT INTO cities (voivodship_id, name) VALUES (20, 'Suwa³ki');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Bytów');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Miastko');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Chojnice');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Brusy');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Czersk');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Cz³uchów');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Czarne');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Debrzno');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Pruszcz Gdañski');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Kartuzy');
INSERT INTO cities (voivodship_id, name) VALUES (22, '¯ukowo');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Koœcierzyna');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Kwidzyn');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Prabuty');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Lêbork');
INSERT INTO cities (voivodship_id, name) VALUES (22, '£eba');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Malbork');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Nowy Staw');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Krynica Morska');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Nowy Dwór Gdañski');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Hel');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Jastarnia');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Puck');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'W³adys³awowo');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Ustka');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Kêpice');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Czarna Woda');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Skórcz');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Starogard Gdañski');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Skarszewy');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Tczew');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Gniew');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Pelplin');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Reda');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Rumia');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Wejherowo');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Dzierzgoñ');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Sztum');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Gdañsk');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Gdynia');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'S³upsk');
INSERT INTO cities (voivodship_id, name) VALUES (22, 'Sopot');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Bêdzin');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'CzeladŸ');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Wojkowice');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Siewierz');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'S³awków');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Szczyrk');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Czechowice-Dziedzice');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Wilamowice');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Cieszyn');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Ustroñ');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Wis³a');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Skoczów');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Strumieñ');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Blachownia');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Koniecpol');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Knurów');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Pyskowice');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Soœnicowice');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Toszek');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'K³obuck');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Krzepice');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Lubliniec');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'WoŸniki');
INSERT INTO cities (voivodship_id, name) VALUES (24, '£aziska Górne');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Miko³ów');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Orzesze');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Myszków');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Kozieg³owy');
INSERT INTO cities (voivodship_id, name) VALUES (24, '¯arki');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Pszczyna');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Racibórz');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Krzanowice');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'KuŸnia Raciborska');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Czerwionka-Leszczyny');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Kalety');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Miasteczko Œl¹skie');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Radzionków');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Tarnowskie Góry');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Bieruñ');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Imielin');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Lêdziny');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Pszów');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Radlin');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Rydu³towy');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Wodzis³aw Œl¹ski');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Porêba');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Zawiercie');
INSERT INTO cities (voivodship_id, name) VALUES (24, '£azy');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Ogrodzieniec');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Pilica');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Szczekociny');
INSERT INTO cities (voivodship_id, name) VALUES (24, '¯ywiec');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Bielsko-Bia³a');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Bytom');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Chorzów');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Czêstochowa');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'D¹browa Górnicza');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Gliwice');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Jastrzêbie-Zdrój');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Jaworzno');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Katowice');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Mys³owice');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Piekary Œl¹skie');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Ruda Œl¹ska');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Rybnik');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Siemianowice Œl¹skie');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Sosnowiec');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Œwiêtoch³owice');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Tychy');
INSERT INTO cities (voivodship_id, name) VALUES (24, 'Zabrze');
INSERT INTO cities (voivodship_id, name) VALUES (24, '¯ory');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'Busko-Zdrój');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'Stopnica');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'Jêdrzejów');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'Ma³ogoszcz');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'Sêdziszów');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'Kazimierza Wielka');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'Skalbmierz');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'Bodzentyn');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'Chêciny');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'Chmielnik');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'Daleszyce');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'Koñskie');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'St¹porków');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'Opatów');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'O¿arów');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'Ostrowiec Œwiêtokrzyski');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'Æmielów');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'Kunów');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'Dzia³oszyce');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'Piñczów');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'Sandomierz');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'Koprzywnica');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'Zawichost');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'Skar¿ysko-Kamienna');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'Suchedniów');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'Starachowice');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'W¹chock');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'Osiek');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'Po³aniec');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'Staszów');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'W³oszczowa');
INSERT INTO cities (voivodship_id, name) VALUES (26, 'Kielce');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Bartoszyce');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Górowo I³aweckie');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Bisztynek');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Sêpopol');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Braniewo');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Frombork');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Pieniê¿no');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Dzia³dowo');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Lidzbark');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'M³ynary');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Pas³êk');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Tolkmicko');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'E³k');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Gi¿ycko');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Ryn');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'I³awa');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Lubawa');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Kisielice');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Susz');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Zalewo');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Kêtrzyn');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Korsze');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Reszel');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Lidzbark Warmiñski');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Orneta');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Mr¹gowo');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Miko³ajki');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Nidzica');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Nowe Miasto Lubawskie');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Olecko');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Barczewo');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Biskupiec');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Dobre Miasto');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Jeziorany');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Olsztynek');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Ostróda');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Mi³akowo');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Mi³om³yn');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Mor¹g');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Bia³a Piska');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Orzysz');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Pisz');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Ruciane-Nida');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Szczytno');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Pasym');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Go³dap');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Wêgorzewo');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Elbl¹g');
INSERT INTO cities (voivodship_id, name) VALUES (28, 'Olsztyn');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Chodzie¿');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Margonin');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Szamocin');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Czarnków');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Krzy¿ Wielkopolski');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Trzcianka');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Wieleñ');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Gniezno');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Czerniejewo');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'K³ecko');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Trzemeszno');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Witkowo');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Borek Wielkopolski');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Gostyñ');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Krobia');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Pogorzela');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Poniec');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Grodzisk Wielkopolski');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Rakoniewice');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Wielichowo');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Jaraczewo');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Jarocin');
INSERT INTO cities (voivodship_id, name) VALUES (30, '¯erków');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Stawiszyn');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Kêpno');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Ko³o');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'D¹bie');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'K³odawa');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Przedecz');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Golina');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Kleczew');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Rychwa³');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Sompolno');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Œlesin');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Koœcian');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Czempiñ');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Krzywiñ');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Œmigiel');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Sulmierzyce');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Kobylin');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'KoŸmin Wielkopolski');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Krotoszyn');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Zduny');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Osieczna');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Rydzyna');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Miêdzychód');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Sieraków');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Lwówek');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Nowy Tomyœl');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Opalenica');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Zb¹szyñ');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Oborniki');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'RogoŸno');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Ostrów Wielkopolski');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Nowe Skalmierzyce');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Odolanów');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Raszków');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Grabów nad Prosn¹');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Mikstat');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Ostrzeszów');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Pi³a');
INSERT INTO cities (voivodship_id, name) VALUES (30, '£ob¿enica');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Ujœcie');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Wyrzysk');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Wysoka');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Chocz');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Dobrzyca');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Pleszew');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Luboñ');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Puszczykowo');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Buk');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Kostrzyn');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Kórnik');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Mosina');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Murowana Goœlina');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Pobiedziska');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Stêszew');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Swarzêdz');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Bojanowo');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Jutrosin');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Miejska Górka');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Rawicz');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'S³upca');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Zagórów');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Obrzycko');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Ostroróg');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Pniewy');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Szamotu³y');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Wronki');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Œroda Wielkopolska');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Dolsk');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Ksi¹¿ Wielkopolski');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Œrem');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Turek');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Dobra');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Tuliszków');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'W¹growiec');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Go³añcz');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Skoki');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Wolsztyn');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Mi³os³aw');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Nekla');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Pyzdry');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Wrzeœnia');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Z³otów');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Jastrowie');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Krajenka');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Okonek');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Kalisz');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Konin');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Leszno');
INSERT INTO cities (voivodship_id, name) VALUES (30, 'Poznañ');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Bia³ogard');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Karlino');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Tychowo');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Choszczno');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Drawno');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Pe³czyce');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Recz');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Czaplinek');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Drawsko Pomorskie');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Kalisz Pomorski');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Z³ocieniec');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Goleniów');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Maszewo');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Nowogard');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Stepnica');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Gryfice');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'P³oty');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Trzebiatów');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Cedynia');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Chojna');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Gryfino');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Mieszkowice');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Moryñ');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Trzciñsko-Zdrój');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Dziwnów');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Golczewo');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Kamieñ Pomorski');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Miêdzyzdroje');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Wolin');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Ko³obrzeg');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Goœcino');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Bobolice');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Polanów');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Sianów');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Barlinek');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Dêbno');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Myœlibórz');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Nowe Warpno');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Police');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Lipiany');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Pyrzyce');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Dar³owo');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'S³awno');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Stargard');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Chociwel');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Dobrzany');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Iñsko');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Suchañ');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Szczecinek');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Barwice');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Bia³y Bór');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Borne Sulinowo');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Œwidwin');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Po³czyn-Zdrój');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Wa³cz');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Cz³opa');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Miros³awiec');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Tuczno');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Dobra');
INSERT INTO cities (voivodship_id, name) VALUES (32, '£obez');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Resko');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Wêgorzyno');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Koszalin');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Szczecin');
INSERT INTO cities (voivodship_id, name) VALUES (32, 'Œwinoujœcie');
commit;